# SPDX-License-Identifier: GPL-2.0
#
# VATICS Clock specific Makefile
#

obj-$(CONFIG_COMMON_CLK_VATICS) += clk-vtx.o

clk-vtx-y += clk.o
clk-vtx-y += clk-pll.o
clk-vtx-y += clk-gate.o
clk-vtx-y += clk-mux.o
clk-vtx-y += clk-div.o
clk-vtx-y += clk-composite.o
clk-vtx-y += clk-fixed-factor.o
clk-vtx-y += clk-phase.o

obj-$(CONFIG_CLK_LEIPZIG)        += clk-leipzig.o clk-leipzig-dbg.o
