/* SPDX-License-Identifier: GPL-2.0-only*/

#define ADDR_IE_CODE            0x0
#define ADDR_IE_CLEN            0x4
#define ADDR_IE_RUN             0x8
#define ADDR_IE_ELEN            0xc
#define ADDR_IE_VER             0x10
#define ADDR_IE_DMA             0x14
#define ADDR_IE_RDMA_SRC0       0x18
#define ADDR_IE_RDMA_SRC1       0x1c
#define ADDR_IE_RDMA_SRC2       0x20
#define ADDR_IE_RDMA_SRC3       0x24
#define ADDR_IE_RDMA_SRC4       0x28
#define ADDR_IE_RDMA_DST0       0x2c
#define ADDR_IE_WDMA_DST0       0x30
#define ADDR_IE_WDMA_DST1       0x34
#define ADDR_IE_WDMA_DST2       0x38
#define ADDR_IE_WDMA_DST3       0x3c
#define ADDR_IE_WDMA_DST4       0x40
#define ADDR_IE_FCON            0x44
#define ADDR_IE_DEWARP          0x48
#define ADDR_IE_DEWARP_CLIP     0x4c
#define ADDR_IE_DEWARP_PX0      0x50
#define ADDR_IE_DEWARP_PY0      0x54
#define ADDR_IE_DEWARP_DELTA0X    0x58
#define ADDR_IE_DEWARP_DELTA1X    0x5c
#define ADDR_IE_DEWARP_DELTA2X    0x60
#define ADDR_IE_DEWARP_DELTA0Y    0x64
#define ADDR_IE_DEWARP_DELTA1Y    0x68
#define ADDR_IE_DEWARP_DELTA2Y    0x6c
#define ADDR_IE_ROTATE          0x70
#define ADDR_IE_ROTATE_1        0x74
#define ADDR_IE_MATRIX          0x78
#define ADDR_IE_MATRIX_1        0x7c
#define ADDR_IE_CC0             0x80
#define ADDR_IE_CC1             0x84
#define ADDR_IE_CC2             0x88
#define ADDR_IE_CC3             0x8c
#define ADDR_IE_CC4             0x90
#define ADDR_IE_CC5             0x94
#define ADDR_IE_CC6             0x98
#define ADDR_IE_SHUFFLE         0x9c
#define ADDR_IE_PACK            0xa0
#define ADDR_IE_FRAME           0xa4
#define ADDR_IE_FDEWARP_END     0xa8
#define ADDR_IE_FDEWARP_CLIP_END    0xac
#define ADDR_IE_FROTATE_END     0xb0
#define ADDR_IE_FMATRIX_END     0xb4
#define ADDR_IE_WDMA_END2       0xb8
#define ADDR_IE_WDMA_END3       0xbc
#define ADDR_IE_IMAGEO0         0xc0
#define ADDR_IE_IMAGEO1         0xc4
#define ADDR_IE_IMAGEI0         0xc8
#define ADDR_IE_IMAGEI1         0xcc
#define ADDR_IE_IMAGEI2         0xd0
#define ADDR_IE_IMAGEI3         0xd4
#define ADDR_IE_IMAGEI4         0xd8
#define ADDR_IE_IMAGEI5         0xdc
#define ADDR_IE_IMAGEI6         0xe0
#define ADDR_IE_IMAGEI7         0xe4
#define ADDR_IE_IMAGEI8         0xe8
#define ADDR_IE_IMAGEI9         0xec
#define ADDR_IE_PRDMA0_SRC0     0xf0
#define ADDR_IE_PRDMA1_SRC0     0xf4
#define ADDR_IE_PWDMA0_DST0     0xf8
#define ADDR_IE_PWDMA1_DST0     0xfc
#define ADDR_IE_INTEN           0x100
#define ADDR_IE_INT             0x104
#define ADDR_IE_LP              0x108
#define ADDR_IE_DBG0            0x10c
#define ADDR_IE_DBG1            0x110
#define ADDR_IE_PROF_CTL        0x114
#define ADDR_IE_PROF            0x118
#define ADDR_IE_DUMMY_0         0x11c
#define ADDR_IE_DUMMY_1         0x120
#define ADDR_IE_DUMMY_2         0x124

#define VAL_ACL(x)    (((x)&0xffff))
#define VAL_ACH(x)    (((x)>>16)&0xffff)
#define ACL_IE_RDMA_SRC0    0xc
#define ACH_IE_RDMA_SRC0    0xd
#define ACL_IE_RDMA_SRC1    0xe
#define ACH_IE_RDMA_SRC1    0xf
#define ACL_IE_RDMA_SRC2    0x10
#define ACH_IE_RDMA_SRC2    0x11
#define ACL_IE_RDMA_SRC3    0x12
#define ACH_IE_RDMA_SRC3    0x13
#define ACL_IE_RDMA_SRC4    0x14
#define ACH_IE_RDMA_SRC4    0x15
#define ACL_IE_RDMA_DST0    0x16
#define ACH_IE_RDMA_DST0    0x17
#define ACL_IE_WDMA_DST0    0x18
#define ACH_IE_WDMA_DST0    0x19
#define ACL_IE_WDMA_DST1    0x1a
#define ACH_IE_WDMA_DST1    0x1b
#define ACL_IE_WDMA_DST2    0x1c
#define ACH_IE_WDMA_DST2    0x1d
#define ACL_IE_WDMA_DST3    0x1e
#define ACH_IE_WDMA_DST3    0x1f
#define ACL_IE_WDMA_DST4    0x20
#define ACH_IE_WDMA_DST4    0x21
#define ACL_IE_FCON         0x22
#define ACH_IE_FCON         0x23
#define ACL_IE_DEWARP       0x24
#define ACH_IE_DEWARP       0x25
#define ACL_IE_DEWARP_CLIP  0x26
#define ACH_IE_DEWARP_CLIP  0x27
#define ACL_IE_DEWARP_PX0   0x28
#define ACH_IE_DEWARP_PX0   0x29
#define ACL_IE_DEWARP_PY0   0x2a
#define ACH_IE_DEWARP_PY0   0x2b
#define ACL_IE_DEWARP_DELTA0X 0x2c
#define ACH_IE_DEWARP_DELTA0X 0x2d
#define ACL_IE_DEWARP_DELTA1X 0x2e
#define ACH_IE_DEWARP_DELTA1X 0x2f
#define ACL_IE_DEWARP_DELTA2X 0x30
#define ACH_IE_DEWARP_DELTA2X 0x31
#define ACL_IE_DEWARP_DELTA0Y 0x32
#define ACH_IE_DEWARP_DELTA0Y 0x33
#define ACL_IE_DEWARP_DELTA1Y 0x34
#define ACH_IE_DEWARP_DELTA1Y 0x35
#define ACL_IE_DEWARP_DELTA2Y 0x36
#define ACH_IE_DEWARP_DELTA2Y 0x37
#define ACL_IE_ROTATE       0x38
#define ACH_IE_ROTATE       0x39
#define ACL_IE_ROTATE_1     0x3a
#define ACH_IE_ROTATE_1     0x3b
#define ACL_IE_MATRIX       0x3c
#define ACH_IE_MATRIX       0x3d
#define ACL_IE_MATRIX_1     0x3e
#define ACH_IE_MATRIX_1     0x3f
#define ACL_IE_CC0          0x40
#define ACH_IE_CC0          0x41
#define ACL_IE_CC1          0x42
#define ACH_IE_CC1          0x43
#define ACL_IE_CC2          0x44
#define ACH_IE_CC2          0x45
#define ACL_IE_CC3          0x46
#define ACH_IE_CC3          0x47
#define ACL_IE_CC4          0x48
#define ACH_IE_CC4          0x49
#define ACL_IE_CC5          0x4a
#define ACH_IE_CC5          0x4b
#define ACL_IE_CC6          0x4c
#define ACH_IE_CC6          0x4d
#define ACL_IE_SHUFFLE      0x4e
#define ACH_IE_SHUFFLE      0x4f
#define ACL_IE_PACK         0x50
#define ACH_IE_PACK         0x51
#define ACL_IE_FRAME        0x52
#define ACH_IE_FRAME        0x53
#define ACL_IE_FDEWARP_END  0x54
#define ACH_IE_FDEWARP_END  0x55
#define ACL_IE_FDEWARP_CLIP_END 0x56
#define ACH_IE_FDEWARP_CLIP_END 0x57
#define ACL_IE_FROTATE_END  0x58
#define ACH_IE_FROTATE_END  0x59
#define ACL_IE_FMATRIX_END  0x5a
#define ACH_IE_FMATRIX_END  0x5b
#define ACL_IE_WDMA_END2    0x5c
#define ACH_IE_WDMA_END2    0x5d
#define ACL_IE_WDMA_END3    0x5e
#define ACH_IE_WDMA_END3    0x5f
#define ACL_IE_IMAGEO0      0x60
#define ACH_IE_IMAGEO0      0x61
#define ACL_IE_IMAGEO1      0x62
#define ACH_IE_IMAGEO1      0x63
#define ACL_IE_IMAGEI0      0x64
#define ACH_IE_IMAGEI0      0x65
#define ACL_IE_IMAGEI1      0x66
#define ACH_IE_IMAGEI1      0x67
#define ACL_IE_IMAGEI2      0x68
#define ACH_IE_IMAGEI2      0x69
#define ACL_IE_IMAGEI3      0x6a
#define ACH_IE_IMAGEI3      0x6b
#define ACL_IE_IMAGEI4      0x6c
#define ACH_IE_IMAGEI4      0x6d
#define ACL_IE_IMAGEI5      0x6e
#define ACH_IE_IMAGEI5      0x6f
#define ACL_IE_IMAGEI6      0x70
#define ACH_IE_IMAGEI6      0x71
#define ACL_IE_IMAGEI7      0x72
#define ACH_IE_IMAGEI7      0x73
#define ACL_IE_IMAGEI8      0x74
#define ACH_IE_IMAGEI8      0x75
#define ACL_IE_IMAGEI9      0x76
#define ACH_IE_IMAGEI9      0x77
#define ACL_IE_PRDMA0_SRC0  0x78
#define ACH_IE_PRDMA0_SRC0  0x79
#define ACL_IE_PRDMA1_SRC0  0x7a
#define ACH_IE_PRDMA1_SRC0  0x7b
#define ACL_IE_PWDMA0_DST0  0x7c
#define ACH_IE_PWDMA0_DST0  0x7d
#define ACL_IE_PWDMA1_DST0  0x7e
#define ACH_IE_PWDMA1_DST0  0x7f

#define IE_CODE_a(x)                    (((x)&0xffffffff)<<0)
#define IE_CLEN_l(x)                    (((x)&0xfffff)<<0)
#define IE_RUN_busy(x)                  (((x)&0x1)<<16)
#define IE_RUN_go(x)                    (((x)&0x1)<<0)
#define IE_ELEN_l(x)                    (((x)&0xfffff)<<0)
#define IE_VER_num(x)                   (((x)&0xffff)<<0)
#define IE_DMA_align_mask(x)            (((x)&0xff)<<24)
#define IE_DMA_wdma(x)                  (((x)&0x3)<<22)
#define IE_DMA_rdma(x)                  (((x)&0x3)<<20)
#define IE_DMA_all(x)                   (((x)&0xf)<<16)
#define IE_DMA_bl(x)                    (((x)&0x1ff)<<0)
#define IE_RDMA_SRC0_sa(x)              (((x)&0xffffffff)<<0)
#define IE_RDMA_SRC1_pitch(x)           (((x)&0xffff)<<0)
#define IE_RDMA_SRC2_len(x)             (((x)&0x1ff)<<0)
#define IE_RDMA_SRC3_line(x)            (((x)&0x7f)<<0)
#define IE_RDMA_SRC4_base(x)            (((x)&0xffffffff)<<0)
#define IE_RDMA_DST0_dl(x)              (((x)&0x7f)<<0)
#define IE_WDMA_DST0_da(x)              (((x)&0xffffffff)<<0)
#define IE_WDMA_DST1_pitch(x)           (((x)&0xffffff)<<0)
#define IE_WDMA_DST2_len(x)             (((x)&0x1ff)<<0)
#define IE_WDMA_DST3_line(x)            (((x)&0x7f)<<0)
#define IE_WDMA_DST4_base(x)            (((x)&0xffffffff)<<0)
#define IE_FCON_nir(x)                  (((x)&0x3)<<9)
#define IE_FCON_alpha(x)                (((x)&0x1)<<8)
#define IE_FCON_iformat_1(x)            (((x)&0x1)<<4)
#define IE_FCON_iformat(x)              (((x)&0xf)<<0)
#define IE_DEWARP_row(x)                (((x)&0x7f)<<24)
#define IE_DEWARP_col(x)                (((x)&0x7f)<<16)
#define IE_DEWARP_CLIP_u_x(x)           (((x)&0x3f)<<8)
#define IE_DEWARP_CLIP_u_y(x)           (((x)&0x3f)<<0)
#define IE_DEWARP_PX0_x(x)              (((x)&0x3fffff)<<0)
#define IE_DEWARP_PY0_y(x)              (((x)&0x3fffff)<<0)
#define IE_DEWARP_DELTA0X_x1(x)         (((x)&0x3fffff)<<0)
#define IE_DEWARP_DELTA1X_x2(x)         (((x)&0x3fffff)<<0)
#define IE_DEWARP_DELTA2X_x3(x)         (((x)&0x3fffff)<<0)
#define IE_DEWARP_DELTA0Y_y1(x)         (((x)&0x3fffff)<<0)
#define IE_DEWARP_DELTA1Y_y2(x)         (((x)&0x3fffff)<<0)
#define IE_DEWARP_DELTA2Y_y3(x)         (((x)&0x3fffff)<<0)
#define IE_ROTATE_row(x)                (((x)&0x7f)<<24)
#define IE_ROTATE_col(x)                (((x)&0x7f)<<16)
#define IE_ROTATE_mode(x)               (((x)&0x7)<<0)
#define IE_ROTATE_1_val(x)              (((x)&0xffffffff)<<0)
#define IE_MATRIX_row(x)                (((x)&0x7f)<<24)
#define IE_MATRIX_col(x)                (((x)&0x7f)<<16)
#define IE_MATRIX_isigned(x)            (((x)&0x1)<<3)
#define IE_MATRIX_osigned(x)            (((x)&0x1)<<2)
#define IE_MATRIX_n(x)                  (((x)&0x1)<<1)
#define IE_MATRIX_csc_sub(x)            (((x)&0x1)<<0)
#define IE_MATRIX_1_csc_sub_sel(x)      (((x)&0x1)<<0)
#define IE_CC0_c01(x)                   (((x)&0xffff)<<16)
#define IE_CC0_c00(x)                   (((x)&0xffff)<<0)
#define IE_CC1_b0(x)                    (((x)&0xffff)<<16)
#define IE_CC1_c02(x)                   (((x)&0xffff)<<0)
#define IE_CC2_c11(x)                   (((x)&0xffff)<<16)
#define IE_CC2_c10(x)                   (((x)&0xffff)<<0)
#define IE_CC3_b1(x)                    (((x)&0xffff)<<16)
#define IE_CC3_c12(x)                   (((x)&0xffff)<<0)
#define IE_CC4_c21(x)                   (((x)&0xffff)<<16)
#define IE_CC4_c20(x)                   (((x)&0xffff)<<0)
#define IE_CC5_b2(x)                    (((x)&0xffff)<<16)
#define IE_CC5_c22(x)                   (((x)&0xffff)<<0)
#define IE_CC6_b3(x)                    (((x)&0xffff)<<16)
#define IE_CC6_c33(x)                   (((x)&0xffff)<<0)
#define IE_SHUFFLE_n(x)                 (((x)&0x7)<<12)
#define IE_SHUFFLE_b(x)                 (((x)&0x7)<<8)
#define IE_SHUFFLE_g(x)                 (((x)&0x7)<<4)
#define IE_SHUFFLE_r(x)                 (((x)&0x7)<<0)
#define IE_PACK_row(x)                  (((x)&0x7f)<<24)
#define IE_PACK_col(x)                  (((x)&0x7f)<<16)
#define IE_PACK_oformat_1(x)            (((x)&0x1)<<4)
#define IE_PACK_oformat(x)              (((x)&0xf)<<0)
#define IE_FRAME_tile_row_num(x)        (((x)&0x1ff)<<16)
#define IE_FRAME_tile_col_num(x)        (((x)&0x1ff)<<0)
#define IE_FDEWARP_END_row(x)           (((x)&0x7f)<<24)
#define IE_FDEWARP_END_col(x)           (((x)&0x7f)<<16)
#define IE_FDEWARP_CLIP_END_u_x(x)      (((x)&0x3f)<<8)
#define IE_FDEWARP_CLIP_END_u_y(x)      (((x)&0x3f)<<0)
#define IE_FROTATE_END_row(x)           (((x)&0x7f)<<24)
#define IE_FROTATE_END_col(x)           (((x)&0x7f)<<16)
#define IE_FMATRIX_END_row(x)           (((x)&0x7f)<<24)
#define IE_FMATRIX_END_col(x)           (((x)&0x7f)<<16)
#define IE_WDMA_END2_col(x)             (((x)&0x7f)<<16)
#define IE_WDMA_END2_len(x)             (((x)&0x1ff)<<0)
#define IE_WDMA_END3_line(x)            (((x)&0x7f)<<0)
#define IE_IMAGEO0_out_row_offset(x)    (((x)&0xffffffff)<<0)
#define IE_IMAGEO1_out_col_offset(x)    (((x)&0x1ff)<<0)
#define IE_IMAGEI0_tile_phase_adj_x(x)  (((x)&0x3fffff)<<0)
#define IE_IMAGEI1_tile_phase_adj_y(x)  (((x)&0x3fffff)<<0)
#define IE_IMAGEI2_corner_phase_x(x)    (((x)&0x7ffffff)<<0)
#define IE_IMAGEI3_corner_phase_y(x)    (((x)&0x7ffffff)<<0)
#define IE_IMAGEI4_corner_phase_col_offset_x(x)  (((x)&0x7ffffff)<<0)
#define IE_IMAGEI5_corner_phase_col_offset_y(x)  (((x)&0x7ffffff)<<0)
#define IE_IMAGEI6_corner_phase_row_offset_x(x)  (((x)&0x7ffffff)<<0)
#define IE_IMAGEI7_corner_phase_row_offset_y(x)  (((x)&0x7ffffff)<<0)
#define IE_IMAGEI8_size_y(x)            (((x)&0x1fff)<<16)
#define IE_IMAGEI8_size_x(x)            (((x)&0x1fff)<<0)
#define IE_IMAGEI9_row_size(x)          (((x)&0x7f)<<16)
#define IE_IMAGEI9_col_size(x)          (((x)&0x7f)<<0)
#define IE_PRDMA0_SRC0_sa(x)            (((x)&0xffffffff)<<0)
#define IE_PRDMA1_SRC0_sa(x)            (((x)&0xffffffff)<<0)
#define IE_PWDMA0_DST0_da(x)            (((x)&0xffffffff)<<0)
#define IE_PWDMA1_DST0_da(x)            (((x)&0xffffffff)<<0)
#define IE_INTEN_done(x)                (((x)&0x1)<<0)
#define IE_INT_done(x)                  (((x)&0x1)<<0)
#define IE_LP_sd_cnt(x)                 (((x)&0xff)<<24)
#define IE_LP_ds_cnt(x)                 (((x)&0xff)<<16)
#define IE_LP_sd(x)                     (((x)&0x1)<<3)
#define IE_LP_ds(x)                     (((x)&0x1)<<2)
#define IE_LP_ls(x)                     (((x)&0x1)<<1)
#define IE_LP_cg(x)                     (((x)&0x1)<<0)
#define IE_DBG0_m(x)                    (((x)&0xff)<<0)
#define IE_DBG1_v(x)                    (((x)&0xffffffff)<<0)
#define IE_PROF_CTL_en(x)               (((x)&0x1)<<0)
#define IE_PROF_cnt(x)                  (((x)&0xffffffff)<<0)
#define IE_DUMMY_0_b(x)                 (((x)&0xffffffff)<<0)
#define IE_DUMMY_1_b(x)                 (((x)&0xffffffff)<<0)
#define IE_DUMMY_2_b(x)                 (((x)&0xffffffff)<<0)

#define PARSE_IE_CODE_a(x)              (((x)>>0)&0xffffffff)
#define PARSE_IE_CLEN_l(x)              (((x)>>0)&0xfffff)
#define PARSE_IE_RUN_busy(x)            (((x)>>16)&0x1)
#define PARSE_IE_RUN_go(x)              (((x)>>0)&0x1)
#define PARSE_IE_ELEN_l(x)              (((x)>>0)&0xfffff)
#define PARSE_IE_VER_num(x)             (((x)>>0)&0xffff)
#define PARSE_IE_DMA_align_mask(x)      (((x)>>24)&0xff)
#define PARSE_IE_DMA_wdma(x)            (((x)>>22)&0x3)
#define PARSE_IE_DMA_rdma(x)            (((x)>>20)&0x3)
#define PARSE_IE_DMA_all(x)             (((x)>>16)&0xf)
#define PARSE_IE_DMA_bl(x)              (((x)>>0)&0x1ff)
#define PARSE_IE_RDMA_SRC0_sa(x)        (((x)>>0)&0xffffffff)
#define PARSE_IE_RDMA_SRC1_pitch(x)     (((x)>>0)&0xffff)
#define PARSE_IE_RDMA_SRC2_len(x)       (((x)>>0)&0x1ff)
#define PARSE_IE_RDMA_SRC3_line(x)      (((x)>>0)&0x7f)
#define PARSE_IE_RDMA_SRC4_base(x)      (((x)>>0)&0xffffffff)
#define PARSE_IE_RDMA_DST0_dl(x)        (((x)>>0)&0x7f)
#define PARSE_IE_WDMA_DST0_da(x)        (((x)>>0)&0xffffffff)
#define PARSE_IE_WDMA_DST1_pitch(x)     (((x)>>0)&0xffffff)
#define PARSE_IE_WDMA_DST2_len(x)       (((x)>>0)&0x1ff)
#define PARSE_IE_WDMA_DST3_line(x)      (((x)>>0)&0x7f)
#define PARSE_IE_WDMA_DST4_base(x)      (((x)>>0)&0xffffffff)
#define PARSE_IE_FCON_nir(x)            (((x)>>9)&0x3)
#define PARSE_IE_FCON_alpha(x)          (((x)>>8)&0x1)
#define PARSE_IE_FCON_iformat_1(x)      (((x)>>4)&0x1)
#define PARSE_IE_FCON_iformat(x)        (((x)>>0)&0xf)
#define PARSE_IE_DEWARP_row(x)          (((x)>>24)&0x7f)
#define PARSE_IE_DEWARP_col(x)          (((x)>>16)&0x7f)
#define PARSE_IE_DEWARP_CLIP_u_x(x)     (((x)>>8)&0x3f)
#define PARSE_IE_DEWARP_CLIP_u_y(x)     (((x)>>0)&0x3f)
#define PARSE_IE_DEWARP_PX0_x(x)        (((x)>>0)&0x3fffff)
#define PARSE_IE_DEWARP_PY0_y(x)        (((x)>>0)&0x3fffff)
#define PARSE_IE_DEWARP_DELTA0X_x1(x)   (((x)>>0)&0x3fffff)
#define PARSE_IE_DEWARP_DELTA1X_x2(x)   (((x)>>0)&0x3fffff)
#define PARSE_IE_DEWARP_DELTA2X_x3(x)   (((x)>>0)&0x3fffff)
#define PARSE_IE_DEWARP_DELTA0Y_y1(x)   (((x)>>0)&0x3fffff)
#define PARSE_IE_DEWARP_DELTA1Y_y2(x)   (((x)>>0)&0x3fffff)
#define PARSE_IE_DEWARP_DELTA2Y_y3(x)   (((x)>>0)&0x3fffff)
#define PARSE_IE_ROTATE_row(x)          (((x)>>24)&0x7f)
#define PARSE_IE_ROTATE_col(x)          (((x)>>16)&0x7f)
#define PARSE_IE_ROTATE_mode(x)         (((x)>>0)&0x7)
#define PARSE_IE_ROTATE_1_val(x)        (((x)>>0)&0xffffffff)
#define PARSE_IE_MATRIX_row(x)          (((x)>>24)&0x7f)
#define PARSE_IE_MATRIX_col(x)          (((x)>>16)&0x7f)
#define PARSE_IE_MATRIX_isigned(x)      (((x)>>3)&0x1)
#define PARSE_IE_MATRIX_osigned(x)      (((x)>>2)&0x1)
#define PARSE_IE_MATRIX_n(x)            (((x)>>1)&0x1)
#define PARSE_IE_MATRIX_csc_sub(x)      (((x)>>0)&0x1)
#define PARSE_IE_MATRIX_1_csc_sub_sel(x)  (((x)>>0)&0x1)
#define PARSE_IE_CC0_c01(x)             (((x)>>16)&0xffff)
#define PARSE_IE_CC0_c00(x)             (((x)>>0)&0xffff)
#define PARSE_IE_CC1_b0(x)              (((x)>>16)&0xffff)
#define PARSE_IE_CC1_c02(x)             (((x)>>0)&0xffff)
#define PARSE_IE_CC2_c11(x)             (((x)>>16)&0xffff)
#define PARSE_IE_CC2_c10(x)             (((x)>>0)&0xffff)
#define PARSE_IE_CC3_b1(x)              (((x)>>16)&0xffff)
#define PARSE_IE_CC3_c12(x)             (((x)>>0)&0xffff)
#define PARSE_IE_CC4_c21(x)             (((x)>>16)&0xffff)
#define PARSE_IE_CC4_c20(x)             (((x)>>0)&0xffff)
#define PARSE_IE_CC5_b2(x)              (((x)>>16)&0xffff)
#define PARSE_IE_CC5_c22(x)             (((x)>>0)&0xffff)
#define PARSE_IE_CC6_b3(x)              (((x)>>16)&0xffff)
#define PARSE_IE_CC6_c33(x)             (((x)>>0)&0xffff)
#define PARSE_IE_SHUFFLE_n(x)           (((x)>>12)&0x7)
#define PARSE_IE_SHUFFLE_b(x)           (((x)>>8)&0x7)
#define PARSE_IE_SHUFFLE_g(x)           (((x)>>4)&0x7)
#define PARSE_IE_SHUFFLE_r(x)           (((x)>>0)&0x7)
#define PARSE_IE_PACK_row(x)            (((x)>>24)&0x7f)
#define PARSE_IE_PACK_col(x)            (((x)>>16)&0x7f)
#define PARSE_IE_PACK_oformat_1(x)      (((x)>>4)&0x1)
#define PARSE_IE_PACK_oformat(x)        (((x)>>0)&0xf)
#define PARSE_IE_FRAME_tile_row_num(x)  (((x)>>16)&0x1ff)
#define PARSE_IE_FRAME_tile_col_num(x)  (((x)>>0)&0x1ff)
#define PARSE_IE_FDEWARP_END_row(x)     (((x)>>24)&0x7f)
#define PARSE_IE_FDEWARP_END_col(x)     (((x)>>16)&0x7f)
#define PARSE_IE_FDEWARP_CLIP_END_u_x(x)  (((x)>>8)&0x3f)
#define PARSE_IE_FDEWARP_CLIP_END_u_y(x)  (((x)>>0)&0x3f)
#define PARSE_IE_FROTATE_END_row(x)     (((x)>>24)&0x7f)
#define PARSE_IE_FROTATE_END_col(x)     (((x)>>16)&0x7f)
#define PARSE_IE_FMATRIX_END_row(x)     (((x)>>24)&0x7f)
#define PARSE_IE_FMATRIX_END_col(x)     (((x)>>16)&0x7f)
#define PARSE_IE_WDMA_END2_col(x)       (((x)>>16)&0x7f)
#define PARSE_IE_WDMA_END2_len(x)       (((x)>>0)&0x1ff)
#define PARSE_IE_WDMA_END3_line(x)      (((x)>>0)&0x7f)
#define PARSE_IE_IMAGEO0_out_row_offset(x)  (((x)>>0)&0xffffffff)
#define PARSE_IE_IMAGEO1_out_col_offset(x)  (((x)>>0)&0x1ff)
#define PARSE_IE_IMAGEI0_tile_phase_adj_x(x)  (((x)>>0)&0x3fffff)
#define PARSE_IE_IMAGEI1_tile_phase_adj_y(x)  (((x)>>0)&0x3fffff)
#define PARSE_IE_IMAGEI2_corner_phase_x(x)  (((x)>>0)&0x7ffffff)
#define PARSE_IE_IMAGEI3_corner_phase_y(x)  (((x)>>0)&0x7ffffff)
#define PARSE_IE_IMAGEI4_corner_phase_col_offset_x(x)  (((x)>>0)&0x7ffffff)
#define PARSE_IE_IMAGEI5_corner_phase_col_offset_y(x)  (((x)>>0)&0x7ffffff)
#define PARSE_IE_IMAGEI6_corner_phase_row_offset_x(x)  (((x)>>0)&0x7ffffff)
#define PARSE_IE_IMAGEI7_corner_phase_row_offset_y(x)  (((x)>>0)&0x7ffffff)
#define PARSE_IE_IMAGEI8_size_y(x)      (((x)>>16)&0x1fff)
#define PARSE_IE_IMAGEI8_size_x(x)      (((x)>>0)&0x1fff)
#define PARSE_IE_IMAGEI9_row_size(x)    (((x)>>16)&0x7f)
#define PARSE_IE_IMAGEI9_col_size(x)    (((x)>>0)&0x7f)
#define PARSE_IE_PRDMA0_SRC0_sa(x)      (((x)>>0)&0xffffffff)
#define PARSE_IE_PRDMA1_SRC0_sa(x)      (((x)>>0)&0xffffffff)
#define PARSE_IE_PWDMA0_DST0_da(x)      (((x)>>0)&0xffffffff)
#define PARSE_IE_PWDMA1_DST0_da(x)      (((x)>>0)&0xffffffff)
#define PARSE_IE_INTEN_done(x)          (((x)>>0)&0x1)
#define PARSE_IE_INT_done(x)            (((x)>>0)&0x1)
#define PARSE_IE_LP_sd_cnt(x)           (((x)>>24)&0xff)
#define PARSE_IE_LP_ds_cnt(x)           (((x)>>16)&0xff)
#define PARSE_IE_LP_sd(x)               (((x)>>3)&0x1)
#define PARSE_IE_LP_ds(x)               (((x)>>2)&0x1)
#define PARSE_IE_LP_ls(x)               (((x)>>1)&0x1)
#define PARSE_IE_LP_cg(x)               (((x)>>0)&0x1)
#define PARSE_IE_DBG0_m(x)              (((x)>>0)&0xff)
#define PARSE_IE_DBG1_v(x)              (((x)>>0)&0xffffffff)
#define PARSE_IE_PROF_CTL_en(x)         (((x)>>0)&0x1)
#define PARSE_IE_PROF_cnt(x)            (((x)>>0)&0xffffffff)
#define PARSE_IE_DUMMY_0_b(x)           (((x)>>0)&0xffffffff)
#define PARSE_IE_DUMMY_1_b(x)           (((x)>>0)&0xffffffff)
#define PARSE_IE_DUMMY_2_b(x)           (((x)>>0)&0xffffffff)
