/* SPDX-License-Identifier: GPL-2.0 */

#ifndef __PINCTRL_LEIPZIG_H__
#define __PINCTRL_LEIPZIG_H__

enum pintype {
	INOUT,
	INPUT,
	OUTPUT,
};

struct leipzig_pintype {
	const enum pintype type;
	const unsigned int type_num;
};

/* define PAD NAME */
#define INOUT_39                        (0)  /* GPIOC_0_IO_DATA_0 */
#define INOUT_40                        (1)
#define INOUT_41                        (2)
#define INOUT_42                        (3)
#define INOUT_43                        (4)
#define INOUT_44                        (5)
#define INOUT_45                        (6)
#define INOUT_46                        (7)
#define INOUT_47                        (8)
#define INOUT_48                        (9)
#define INOUT_49                        (10)
#define INOUT_50                        (11)
#define INOUT_51                        (12)
#define INOUT_52                        (13)
#define INOUT_53                        (14)
#define INOUT_54                        (15)
#define INOUT_55                        (16)
#define INOUT_56                        (17)
#define INOUT_57                        (18)
#define INOUT_58                        (19)
#define INOUT_59                        (20)
#define INOUT_60                        (21)
#define INOUT_61                        (22)
#define INOUT_62                        (23)
#define INOUT_63                        (24)
#define INOUT_64                        (25)
#define INOUT_65                        (26)
#define INOUT_66                        (27)
#define INOUT_67                        (28)
#define INOUT_68                        (29)
#define INOUT_69                        (30)
#define INOUT_70                        (31) /* GPIOC_0_IO_DATA_31 */
#define INOUT_71                        (32) /* GPIOC_1_IO_DATA_0 */
#define INOUT_72                        (33)
#define INOUT_73                        (34)
#define INOUT_74                        (35)
#define INOUT_75                        (36)
#define INOUT_76                        (37)
#define INOUT_77                        (38)
#define INOUT_78                        (39)
#define INOUT_79                        (40)
#define INOUT_80                        (41)
#define INOUT_81                        (42)
#define INOUT_82                        (43)
#define INOUT_83                        (44)
#define INOUT_84                        (45)
#define INOUT_85                        (46)
#define INOUT_86                        (47)
#define INOUT_87                        (48)
#define INOUT_88                        (49)
#define INOUT_89                        (50)
#define INOUT_90                        (51)
#define INOUT_91                        (52)
#define INOUT_92                        (53)
#define INOUT_93                        (54)
#define INOUT_94                        (55)
#define INOUT_95                        (56)
#define INOUT_0                         (57)
#define INOUT_1                         (58)
#define INOUT_2                         (59)
#define INOUT_3                         (60)
#define INOUT_4                         (61)
#define INOUT_5                         (62)
#define INOUT_6                         (63) /* GPIOC_1_IO_DATA_31 */
#define INOUT_7                         (64) /* GPIOC_2_IO_DATA_0 */
#define INOUT_8                         (65)
#define INOUT_9                         (66)
#define INOUT_10                        (67)
#define INOUT_11                        (68)
#define INOUT_12                        (69)
#define INOUT_13                        (70)
#define INOUT_14                        (71)
#define INOUT_15                        (72)
#define INOUT_16                        (73)
#define INOUT_17                        (74)
#define INOUT_18                        (75)
#define INOUT_19                        (76)
#define INOUT_20                        (77)
#define INOUT_21                        (78)
#define INOUT_22                        (79)
#define INOUT_23                        (80)
#define INOUT_24                        (81)
#define INOUT_25                        (82)
#define INOUT_26                        (83)
#define INOUT_27                        (84)
#define INOUT_28                        (85)
#define INOUT_29                        (86)
#define INOUT_30                        (87)
#define INOUT_31                        (88)
#define INOUT_32                        (89)
#define INOUT_33                        (90)
#define INOUT_34                        (91)
#define INOUT_35                        (92)
#define INOUT_36                        (93)
#define INOUT_37                        (94)
#define INOUT_38                        (95) /* GPIOC_2_IO_DATA_31 */

#define OUTPUT_0                        (96)
#define OUTPUT_1                        (97)
#define OUTPUT_2                        (98)
#define OUTPUT_3                        (99)
#define OUTPUT_4                        (100)
#define OUTPUT_5                        (101)

#define INPUT_0                         (102)
#define INPUT_1                         (103)
#define INPUT_2                         (104)
#define INPUT_3                         (105)
#define INPUT_4                         (106)
#define INPUT_5                         (107)
#define INPUT_6                         (108)
#define INPUT_7                         (109)
#define INPUT_8                         (110)
#define INPUT_9                         (111)


#define DECLARE_PINS_TYPE(_name, _type, _type_num) \
const struct leipzig_pintype _name##_##_type_num##_pintype = { \
	.type = _type, \
	.type_num = _type_num, \
}

DECLARE_PINS_TYPE(inout, INOUT, 0);
DECLARE_PINS_TYPE(inout, INOUT, 1);
DECLARE_PINS_TYPE(inout, INOUT, 2);
DECLARE_PINS_TYPE(inout, INOUT, 3);
DECLARE_PINS_TYPE(inout, INOUT, 4);
DECLARE_PINS_TYPE(inout, INOUT, 5);
DECLARE_PINS_TYPE(inout, INOUT, 6);
DECLARE_PINS_TYPE(inout, INOUT, 7);
DECLARE_PINS_TYPE(inout, INOUT, 8);
DECLARE_PINS_TYPE(inout, INOUT, 9);
DECLARE_PINS_TYPE(inout, INOUT, 10);
DECLARE_PINS_TYPE(inout, INOUT, 11);
DECLARE_PINS_TYPE(inout, INOUT, 12);
DECLARE_PINS_TYPE(inout, INOUT, 13);
DECLARE_PINS_TYPE(inout, INOUT, 14);
DECLARE_PINS_TYPE(inout, INOUT, 15);
DECLARE_PINS_TYPE(inout, INOUT, 16);
DECLARE_PINS_TYPE(inout, INOUT, 17);
DECLARE_PINS_TYPE(inout, INOUT, 18);
DECLARE_PINS_TYPE(inout, INOUT, 19);
DECLARE_PINS_TYPE(inout, INOUT, 20);
DECLARE_PINS_TYPE(inout, INOUT, 21);
DECLARE_PINS_TYPE(inout, INOUT, 22);
DECLARE_PINS_TYPE(inout, INOUT, 23);
DECLARE_PINS_TYPE(inout, INOUT, 24);
DECLARE_PINS_TYPE(inout, INOUT, 25);
DECLARE_PINS_TYPE(inout, INOUT, 26);
DECLARE_PINS_TYPE(inout, INOUT, 27);
DECLARE_PINS_TYPE(inout, INOUT, 28);
DECLARE_PINS_TYPE(inout, INOUT, 29);
DECLARE_PINS_TYPE(inout, INOUT, 30);
DECLARE_PINS_TYPE(inout, INOUT, 31);
DECLARE_PINS_TYPE(inout, INOUT, 32);
DECLARE_PINS_TYPE(inout, INOUT, 33);
DECLARE_PINS_TYPE(inout, INOUT, 34);
DECLARE_PINS_TYPE(inout, INOUT, 35);
DECLARE_PINS_TYPE(inout, INOUT, 36);
DECLARE_PINS_TYPE(inout, INOUT, 37);
DECLARE_PINS_TYPE(inout, INOUT, 38);
DECLARE_PINS_TYPE(inout, INOUT, 39);
DECLARE_PINS_TYPE(inout, INOUT, 40);
DECLARE_PINS_TYPE(inout, INOUT, 41);
DECLARE_PINS_TYPE(inout, INOUT, 42);
DECLARE_PINS_TYPE(inout, INOUT, 43);
DECLARE_PINS_TYPE(inout, INOUT, 44);
DECLARE_PINS_TYPE(inout, INOUT, 45);
DECLARE_PINS_TYPE(inout, INOUT, 46);
DECLARE_PINS_TYPE(inout, INOUT, 47);
DECLARE_PINS_TYPE(inout, INOUT, 48);
DECLARE_PINS_TYPE(inout, INOUT, 49);
DECLARE_PINS_TYPE(inout, INOUT, 50);
DECLARE_PINS_TYPE(inout, INOUT, 51);
DECLARE_PINS_TYPE(inout, INOUT, 52);
DECLARE_PINS_TYPE(inout, INOUT, 53);
DECLARE_PINS_TYPE(inout, INOUT, 54);
DECLARE_PINS_TYPE(inout, INOUT, 55);
DECLARE_PINS_TYPE(inout, INOUT, 56);
DECLARE_PINS_TYPE(inout, INOUT, 57);
DECLARE_PINS_TYPE(inout, INOUT, 58);
DECLARE_PINS_TYPE(inout, INOUT, 59);
DECLARE_PINS_TYPE(inout, INOUT, 60);
DECLARE_PINS_TYPE(inout, INOUT, 61);
DECLARE_PINS_TYPE(inout, INOUT, 62);
DECLARE_PINS_TYPE(inout, INOUT, 63);
DECLARE_PINS_TYPE(inout, INOUT, 64);
DECLARE_PINS_TYPE(inout, INOUT, 65);
DECLARE_PINS_TYPE(inout, INOUT, 66);
DECLARE_PINS_TYPE(inout, INOUT, 67);
DECLARE_PINS_TYPE(inout, INOUT, 68);
DECLARE_PINS_TYPE(inout, INOUT, 69);
DECLARE_PINS_TYPE(inout, INOUT, 70);
DECLARE_PINS_TYPE(inout, INOUT, 71);
DECLARE_PINS_TYPE(inout, INOUT, 72);
DECLARE_PINS_TYPE(inout, INOUT, 73);
DECLARE_PINS_TYPE(inout, INOUT, 74);
DECLARE_PINS_TYPE(inout, INOUT, 75);
DECLARE_PINS_TYPE(inout, INOUT, 76);
DECLARE_PINS_TYPE(inout, INOUT, 77);
DECLARE_PINS_TYPE(inout, INOUT, 78);
DECLARE_PINS_TYPE(inout, INOUT, 79);
DECLARE_PINS_TYPE(inout, INOUT, 80);
DECLARE_PINS_TYPE(inout, INOUT, 81);
DECLARE_PINS_TYPE(inout, INOUT, 82);
DECLARE_PINS_TYPE(inout, INOUT, 83);
DECLARE_PINS_TYPE(inout, INOUT, 84);
DECLARE_PINS_TYPE(inout, INOUT, 85);
DECLARE_PINS_TYPE(inout, INOUT, 86);
DECLARE_PINS_TYPE(inout, INOUT, 87);
DECLARE_PINS_TYPE(inout, INOUT, 88);
DECLARE_PINS_TYPE(inout, INOUT, 89);
DECLARE_PINS_TYPE(inout, INOUT, 90);
DECLARE_PINS_TYPE(inout, INOUT, 91);
DECLARE_PINS_TYPE(inout, INOUT, 92);
DECLARE_PINS_TYPE(inout, INOUT, 93);
DECLARE_PINS_TYPE(inout, INOUT, 94);
DECLARE_PINS_TYPE(inout, INOUT, 95);
DECLARE_PINS_TYPE(inout, INOUT, 96);
DECLARE_PINS_TYPE(inout, INOUT, 97);
DECLARE_PINS_TYPE(inout, INOUT, 98);
DECLARE_PINS_TYPE(inout, INOUT, 99);
DECLARE_PINS_TYPE(inout, INOUT, 100);
DECLARE_PINS_TYPE(inout, INOUT, 101);

DECLARE_PINS_TYPE(input, INPUT, 0);
DECLARE_PINS_TYPE(input, INPUT, 1);
DECLARE_PINS_TYPE(input, INPUT, 2);
DECLARE_PINS_TYPE(input, INPUT, 3);
DECLARE_PINS_TYPE(input, INPUT, 4);
DECLARE_PINS_TYPE(input, INPUT, 5);
DECLARE_PINS_TYPE(input, INPUT, 6);
DECLARE_PINS_TYPE(input, INPUT, 7);
DECLARE_PINS_TYPE(input, INPUT, 8);
DECLARE_PINS_TYPE(input, INPUT, 9);

DECLARE_PINS_TYPE(output, OUTPUT, 0);
DECLARE_PINS_TYPE(output, OUTPUT, 1);
DECLARE_PINS_TYPE(output, OUTPUT, 2);
DECLARE_PINS_TYPE(output, OUTPUT, 3);
DECLARE_PINS_TYPE(output, OUTPUT, 4);
DECLARE_PINS_TYPE(output, OUTPUT, 5);
DECLARE_PINS_TYPE(output, OUTPUT, 6);
DECLARE_PINS_TYPE(output, OUTPUT, 7);
DECLARE_PINS_TYPE(output, OUTPUT, 8);
DECLARE_PINS_TYPE(output, OUTPUT, 9);

/* define FUNCTION NAME */
#define SCRTU_DBG                       (0)
#define CA55U_DBG                       (1)
#define USB30C_DBG                      (2)
#define VQ7U_DBG                        (3)
#define SSIC3_SGL_MA                    (4)
#define SSIC2_SGL_MA                    (5)
#define SSIC1_SGL_MA                    (6)
#define SSIC0_SGL_SLA                   (7)
#define SSIC0_SGL_MA                    (8)
#define SSIC0_QUAD_MA                   (9)
#define MSHC                            (10)
#define MONITOR_CLK                     (11)
#define IRDAC                           (12)
#define I2SSC_TX_SLA                    (13)
#define I2SSC_TX_MA                     (14)
#define I2SSC_RX_SLA                    (15)
#define I2SSC_RX_MA                     (16)
#define I2SSC_MA_CLK                    (17)
#define I2CC2_POS1                      (18)
#define I2CC2_POS0                      (19)
#define I2CC1_POS1                      (20)
#define I2CC1_POS0                      (21)
#define I2CC0                           (22)
#define EQOSC_TX_OUT_CLK                (23)
#define EQOSC_TX_IN_CLK                 (24)
#define EQOSC_RX_CLK                    (25)
#define EQOSC_REF_CLK                   (26)
#define EQOSC_SEC3                      (27)
#define EQOSC_SEC2                      (28)
#define EQOSC_SEC1                      (29)
#define EQOSC_SEC0                      (30)
#define DDRNSDMC_TEST                   (31)
#define ADCDCC                          (32)
#define USB30C_VBUS_OC			(33)
#define USB30C_DRV_VBUS			(34)
#define USB20C_VBUS_OC			(35)
#define USB20C_DRV_VBUS			(36)
#define UART4_POS2                      (37)
#define UART4_POS1                      (38)
#define UART4_POS0                      (39)
#define UART3_POS2                      (40)
#define UART3_POS1                      (41)
#define UART3_POS0                      (42)
#define UART2_POS2                      (43)
#define UART2_POS1                      (44)
#define UART2_POS0                      (45)
#define UART1_POS2_SEC1                 (46)
#define UART1_POS2_SEC0                 (47)
#define UART1_POS1_SEC1                 (48)
#define UART1_POS1_SEC0                 (49)
#define UART1_POS0_SEC1                 (50)
#define UART1_POS0_SEC0                 (51)
#define UART0_POS2_SEC1                 (52)
#define UART0_POS2_SEC0                 (53)
#define UART0_POS1_SEC1                 (54)
#define UART0_POS1_SEC0                 (55)
#define UART0_POS0_SEC1                 (56)
#define UART0_POS0_SEC0                 (57)
#define WDTC                            (58)
#define VOC1_SEC7_POS1                  (59)
#define VOC1_SEC7_POS0                  (60)
#define VOC1_SEC6                       (61)
#define VOC1_SEC5                       (62)
#define VOC1_SEC4                       (63)
#define VOC1_SEC3_POS1                  (64)
#define VOC1_SEC3_POS0                  (65)
#define VOC1_SEC2_POS1                  (66)
#define VOC1_SEC2_POS0                  (67)
#define VOC1_SEC1                       (68)
#define VOC1_SEC0                       (69)
#define VOC1_CLK_POS1                   (70)
#define VOC1_CLK_POS0                   (71)
#define VIC1_SEC5                       (72)
#define VIC1_SEC4                       (73)
#define VIC1_SEC3                       (74)
#define VIC1_SEC2                       (75)
#define VIC1_SEC1                       (76)
#define VIC1_SEC0                       (77)
#define VIC0_SEC5                       (78)
#define VIC0_SEC4                       (79)
#define VIC0_SEC3                       (80)
#define VIC0_SEC2                       (81)
#define VIC0_SEC1                       (82)
#define VIC0_SEC0                       (83)
#define VIC_REF_SYNC                    (84)
#define VIC_REF_CLK                     (85)
#define AGPO0_POS0                      (86)
#define AGPO1_POS0                      (87)
#define AGPO2_POS0                      (88)
#define AGPO3_POS0                      (89)
#define AGPO4_POS0                      (90)
#define AGPO5_POS0                      (91)
#define AGPO6_POS0                      (92)
#define AGPO7_POS0                      (93)
#define AGPO8_POS0                      (94)
#define AGPO9_POS0                      (95)
#define AGPO10_POS0                     (96)
#define AGPO11_POS0                     (97)
#define AGPO0_POS1                      (98)
#define AGPO1_POS1                      (99)
#define AGPO2_POS1                      (100)
#define AGPO3_POS1                      (101)
#define AGPO4_POS1                      (102)
#define AGPO5_POS1                      (103)
#define AGPO6_POS1                      (104)
#define AGPO7_POS1                      (105)
#define AGPO8_POS1                      (106)
#define AGPO9_POS1                      (107)
#define AGPO10_POS1                     (108)
#define AGPO11_POS1                     (109)
#define AGPO0_POS2                      (110)
#define AGPO1_POS2                      (111)
#define AGPO2_POS2                      (112)
#define AGPO3_POS2                      (113)
#define AGPO4_POS2                      (114)
#define AGPO5_POS2                      (115)
#define AGPO6_POS2                      (116)
#define AGPO7_POS2                      (117)
#define AGPO8_POS2                      (118)
#define AGPO9_POS2                      (119)
#define AGPO10_POS2                     (120)
#define AGPO11_POS2                     (121)
#define AGPO0_POS3                      (122)
#define AGPO1_POS3                      (123)
#define AGPO2_POS3                      (124)
#define AGPO3_POS3                      (125)
#define AGPO4_POS3                      (126)
#define AGPO5_POS3                      (127)
#define AGPO6_POS3                      (128)
#define AGPO7_POS3                      (129)
#define AGPO8_POS3                      (130)
#define AGPO9_POS3                      (131)
#define AGPO10_POS3                     (132)
#define AGPO11_POS3                     (133)
#define AGPO0_POS4                      (134)
#define AGPO1_POS4                      (135)
#define AGPO2_POS4                      (136)
#define AGPO3_POS4                      (137)
#define AGPO4_POS4                      (138)
#define AGPO5_POS4                      (139)
#define AGPO6_POS4                      (140)
#define AGPO7_POS4                      (141)
#define AGPO8_POS4                      (142)
#define AGPO9_POS4                      (143)
#define AGPO10_POS4                     (144)
#define AGPO11_POS4                     (145)
#define GPIO0_DATA0                     (146)
#define GPIO0_DATA1                     (147)
#define GPIO0_DATA2                     (148)
#define GPIO0_DATA3                     (149)
#define GPIO0_DATA4                     (150)
#define GPIO0_DATA5                     (151)
#define GPIO0_DATA6                     (152)
#define GPIO0_DATA7                     (153)
#define GPIO0_DATA8                     (154)
#define GPIO0_DATA9                     (155)
#define GPIO0_DATA10                    (156)
#define GPIO0_DATA11                    (157)
#define GPIO0_DATA12                    (158)
#define GPIO0_DATA13                    (159)
#define GPIO0_DATA14                    (160)
#define GPIO0_DATA15                    (161)
#define GPIO0_DATA16                    (162)
#define GPIO0_DATA17                    (163)
#define GPIO0_DATA18                    (164)
#define GPIO0_DATA19                    (165)
#define GPIO0_DATA20                    (166)
#define GPIO0_DATA21                    (167)
#define GPIO0_DATA22                    (168)
#define GPIO0_DATA23                    (169)
#define GPIO0_DATA24                    (170)
#define GPIO0_DATA25                    (171)
#define GPIO0_DATA26                    (172)
#define GPIO0_DATA27                    (173)
#define GPIO0_DATA28                    (174)
#define GPIO0_DATA29                    (175)
#define GPIO0_DATA30                    (176)
#define GPIO0_DATA31                    (177)
#define GPIO1_DATA0                     (178)
#define GPIO1_DATA1                     (179)
#define GPIO1_DATA2                     (180)
#define GPIO1_DATA3                     (181)
#define GPIO1_DATA4                     (182)
#define GPIO1_DATA5                     (183)
#define GPIO1_DATA6                     (184)
#define GPIO1_DATA7                     (185)
#define GPIO1_DATA8                     (186)
#define GPIO1_DATA9                     (187)
#define GPIO1_DATA10                    (188)
#define GPIO1_DATA11                    (189)
#define GPIO1_DATA12                    (190)
#define GPIO1_DATA13                    (191)
#define GPIO1_DATA14                    (192)
#define GPIO1_DATA15                    (193)
#define GPIO1_DATA16                    (194)
#define GPIO1_DATA17                    (195)
#define GPIO1_DATA18                    (196)
#define GPIO1_DATA19                    (197)
#define GPIO1_DATA20                    (198)
#define GPIO1_DATA21                    (199)
#define GPIO1_DATA22                    (200)
#define GPIO1_DATA23                    (201)
#define GPIO1_DATA24                    (202)
#define GPIO1_DATA25                    (203)
#define GPIO1_DATA26                    (204)
#define GPIO1_DATA27                    (205)
#define GPIO1_DATA28                    (206)
#define GPIO1_DATA29                    (207)
#define GPIO1_DATA30                    (208)
#define GPIO1_DATA31                    (209)
#define GPIO2_DATA0                     (210)
#define GPIO2_DATA1                     (211)
#define GPIO2_DATA2                     (212)
#define GPIO2_DATA3                     (213)
#define GPIO2_DATA4                     (214)
#define GPIO2_DATA5                     (215)
#define GPIO2_DATA6                     (216)
#define GPIO2_DATA7                     (217)
#define GPIO2_DATA8                     (218)
#define GPIO2_DATA9                     (219)
#define GPIO2_DATA10                    (220)
#define GPIO2_DATA11                    (221)
#define GPIO2_DATA12                    (222)
#define GPIO2_DATA13                    (223)
#define GPIO2_DATA14                    (224)
#define GPIO2_DATA15                    (225)
#define GPIO2_DATA16                    (226)
#define GPIO2_DATA17                    (227)
#define GPIO2_DATA18                    (228)
#define GPIO2_DATA19                    (229)
#define GPIO2_DATA20                    (230)
#define GPIO2_DATA21                    (231)
#define GPIO2_DATA22                    (232)
#define GPIO2_DATA23                    (233)
#define GPIO2_DATA24                    (234)
#define GPIO2_DATA25                    (235)
#define GPIO2_DATA26                    (236)
#define GPIO2_DATA27                    (237)
#define GPIO2_DATA28                    (238)
#define GPIO2_DATA29                    (239)
#define GPIO2_DATA30                    (240)
#define GPIO2_DATA31                    (241)

#define GPIO_NUMS			96
#define GPIO_GROUP_OFFSET		GPIO0_DATA0

#endif /*__PINMUX_LEIPZIG_H__*/
