# SPDX-License-Identifier: GPL-2.0

######################################################
# VATICS Platform Support
######################################################
obj-$(CONFIG_ARCH_LEIPZIG) += leipzig/
#obj-$(CONFIG_ARCH_VIENNA) += vienna/

######################################################
# Audio Codec Driver
######################################################
snd-soc-vtx-codec-ssm2603-objs := ssm2603.o

obj-$(CONFIG_SND_SOC_VTX_CODEC_SSM2603) += snd-soc-vtx-codec-ssm2603.o


