dtb-y += leipzig-fpga.dtb
dtb-y += leipzig.dtb
dtb-y += leipzig-klink.dtb
dtb-y += leipzig-evm-it66121.dtb
dtb-y += leipzig-evm-multi-sensor.dtb
dtb-y += leipzig-hdk-3ch.dtb
dtb-y += leipzig-hdk-2ch.dtb
dtb-y += leipzig-hdk-kneo-pi.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
